# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'Default'
  vmImage: ubuntu-latest

steps:
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'rgconn'
    appName: 'mytestappsvc'
    containers: 'mytesdockregistry.azurecr.io/app/aegis:latest'
    appSettings: '-PORT 80 -DOCKER_REGISTRY_SERVER_PASSWORD ${acr-pass} -DOCKER_REGISTRY_SERVER_URL https://mytesdockregistry.azurecr.io -DOCKER_REGISTRY_SERVER_USERNAME mytesdockregistry''


