# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'Default'
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'acrconn'
    repository: 'app/aegis'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'rgconn'
    appName: 'mytestappsvc'
    containers: 'mytesdockregistry.azurecr.io/app/aegis:latest'
    appSettings: '-DOCKER_REGISTRY_SERVER_PASSWORD $(acr-pass) -DOCKER_REGISTRY_SERVER_URL https://mytesdockregistry.azurecr.io -DOCKER_REGISTRY_SERVER_USERNAME mytesdockregistry'
- task: Npm@1
  inputs:
    command: 'publish'
    verbose: true
    publishRegistry: 'useFeed'
    publishFeed: '200edbc6-24d3-4f4c-9d0f-2d1d879379f4'